import { NextRequest, NextResponse } from 'next/server';

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/get-passport?id=DPP-2024-XXXXX
//
// Reads a Digital Product Passport from Firestore (Admin SDK — `passports`
// collection) and returns it as JSON.  This endpoint is used by the public
// passport page when the DPP was NOT stored on the scan record (e.g. the scan
// was made while the user was unauthenticated, or the DPP was generated by the
// API and stored server-side only).
//
// Returns:
//   200  { success: true, dpp: DigitalProductPassport }
//   400  { success: false, error: "Missing passport ID" }
//   404  { success: false, error: "Passport not found" }
//   500  { success: false, error: "..." }
// ─────────────────────────────────────────────────────────────────────────────

export async function GET(request: NextRequest) {
    const passportId = request.nextUrl.searchParams.get('id')?.trim();

    if (!passportId) {
        return NextResponse.json({ success: false, error: 'Missing passport ID.' }, { status: 400 });
    }

    const projectId = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
    if (!projectId) {
        return NextResponse.json({ success: false, error: 'Firebase not configured.' }, { status: 500 });
    }

    try {
        const { initializeApp, getApps, cert } = await import('firebase-admin/app');
        const { getFirestore } = await import('firebase-admin/firestore');

        if (!getApps().length) {
            let rawJson = process.env.FIREBASE_SERVICE_ACCOUNT_JSON ?? '{}';
            rawJson = rawJson.trim();
            if ((rawJson.startsWith("'") && rawJson.endsWith("'")) ||
                (rawJson.startsWith('"') && rawJson.endsWith('"'))) {
                rawJson = rawJson.slice(1, -1);
            }
            rawJson = rawJson.replace(/\\n/g, '\n');
            const serviceAccount = JSON.parse(rawJson) as Record<string, unknown>;
            if (serviceAccount.project_id) {
                initializeApp({ credential: cert(serviceAccount as Parameters<typeof cert>[0]) });
            } else {
                initializeApp({ projectId });
            }
            getFirestore().settings({ ignoreUndefinedProperties: true });
        }

        const db = getFirestore();

        // Try `passports` collection first (written by generate-dpp)
        const passportSnap = await db.collection('passports').doc(passportId).get();
        if (passportSnap.exists) {
            return NextResponse.json({ success: true, dpp: passportSnap.data() });
        }

        // Fallback: search `scans` by passportId field
        const scansSnap = await db
            .collection('scans')
            .where('passportId', '==', passportId)
            .limit(1)
            .get();

        if (!scansSnap.empty) {
            const scanData = scansSnap.docs[0].data() as { dpp?: string };
            if (scanData.dpp && scanData.dpp !== '{}') {
                return NextResponse.json({ success: true, dpp: JSON.parse(scanData.dpp) });
            }
        }

        return NextResponse.json({ success: false, error: 'Passport not found.' }, { status: 404 });
    } catch (error) {
        console.error('[get-passport]', error);
        return NextResponse.json(
            { success: false, error: error instanceof Error ? error.message : 'Failed to load passport.' },
            { status: 500 },
        );
    }
}
